language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
script: nosetests
deploy:
  provider: heroku
  api_key:
    secure: U1K6bHi9xRHKWfmKUt5qvYKhxSQEwcjicGIylFvHtGCdRWYDTknIAhqpeHpGJrKetupfOP/IsgJajjGVjUesizExVtYRKe1fcmzMw0veTbKxqpNoaofsuNMQkA+rh4Yt3gWOJ9iU0bhdTNceOXAbD6w2RYOu3Se7VGlmb8HZKk2WL+fNUpKS1t4TOkTaXIoUm+50DZJfAL0fWaiyyf6Qa0jYMxWMI+JPc+iYUi6FD6DrHhBk8smyexuiaUmfpmD81pQaDJQ17e4N0LNSKn8MFueUVttJOV90giSNg3imY6MHMoX+FnHevv/LYr9vdcxo6m2lrYgmM5vSSPK4gV1zDJCN1er46sZStRBwuoduoqo5woQk12UqNqfwlPi6hD3uCrDro4MAs1FPKSiFcL0vtMVw03/JWGudYrOJUB4ah8Vws2yom1795PeSBQwG7LlpdnXSSA8D2BP9A5lruUqPuFETNxgO6723/M0o7M+OP40JH9b02cTrQrVqIMBInH6QrbcBCrSJFlYI/eueTDhJFwj8+ANZs8F23SdPnh3f6Ti/72ygGDBt84DlorcihZ2ul8xeXGUVzglZqPv1uSAIcPK/UfHFvcjs8/cBVnMxe8/GeUOMSXpIsoLoDpOtT7WQtenNCWtoWnTYxot9oWXpHAu6kAxCXMhDNs9TPBjKnUk=
  app: limitless-tundra-8727
  on:
    repo: xirain/flasktaskr
