language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
script: nosetests
deploy:
  provider: heroku
  api_key:
    secure: MKk7vc+jtAt3dODyjkXLG9pd+IUAOe50WvCol5NlZU7qDtL24CAtDRSgcZqNigIq46MwHwl8MDXvBc5FOCBHZCm0+6vXGpTzR21Jq+99jzfoIfftS6sTHxnaLkh9SwbG9yTg1Cbko9AtbwMlqi7HcvvJpjHEW42ME/mu2frvCqi5S0xPHCjfufw6DuPnToYFLQCWusmC+nf6Ji9NCWSFs4dBXCloVmQ5FL0mN5BGHQAnMDg5Fby3W5j1/0vVtREPhpdHx7GJMJM2UaG40HGdqzH7LyKZ63AOXWVgGFKlF3TC5S2D99RriaiI85mdyXWzEwY4qGTRqIk5KlExBkSu9humJ6WbK3Drb8hZqgiWQC0su0nw5KG4ab7zSPtgjpdQzWo1nU/7viyAcn2sV+Tqo59E8bf5Fd8d8+BqWiz9YV4+ypAMHeTE9XHECggIbgmt4/PbkJbaNAamdhy1XkW1cZyKtqgCbi225gtob0JRLuUheKKeUp1cyPsBNeMeknIs8sSf1xktl0qNYiH29f/atUgLCnvJ14JhGExYBlRu0yxDc28gSnocRcQWEKRYh3VqrO1ymBHwhtcFoy62tjzF+ghNgRBQlzbXj7WOhKY+hIJMh842ybf0/+1GOgZdvRIX1DRtWCQZYZXyphBQRbJAs5PsVwoUfa77fPbTjmQYykk=
  app: limitless-tundra-8727
  on:
    repo: xirain/flasktaskr
