language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
script: nosetests
deploy:
  provider: heroku
  api_key:
    secure: Oo6a7F4k5Ffm7a5i+vziRjdwAWToUB1/y3E49MVWYbyO884zbSCN0AJpxOm+ny5NHEqe0ybqfL2q+rCKxaxck3CVjdx3/gorPkrWsfsnWRFsEl4sO4/qMw4MMSX3t6+1uTxUGaOgMdNeyhM0IkkallYhVtN0E1tjnfqKqjMqM5ZyHyC237WwukZA3OG9FmpPJhNxPoxcy/B2DVYtSQtAwbYCUIdLfApl1/ShCq+L6qfKh0Oxo6gjIEKFJdlWZ36wD3eRtCdk8ufKhmNbenCM7pXAXWvJhO8fFa2UumvJ+ZIMeqeAagYVSJensCXQYLQnTaI0EfxF7efGNHtXdh6TkydyPdbgEg05HNWZAqAIrOjRgyCr3iG1As72N2ER8qImKftoV7x0UgWPDV/hS6MqnCKxq/iyFqOQj6DQCipZNVWoGhS6EmCWhrywRwjRTquYNFjXWwW9GPtKLjkZPi0CXZtS1d9z293X4iG9hCKbhim0CwjfwnbKHesUx4zyntx6XU+ZIEgWrTyqv9nikIh2AOFrgnpkNMr8aUB888+3oDRNpJJS7rNNLK0zuY55Ragr2CsbCfSZNGBPx1C2cXZeDHP2w67czqk59N3aHnWTbOMCRU9zmC9U+qHMentjqScy+IE80kekJ7HcI/dpcaKfahdb/8uxZU7jDkxCLnaP5+I=
  app: flasktask
  on:
    repo: xirain/flasktaskr
