language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
script: nosetests
deploy:
  provider: heroku
  api_key:
    secure: q3xXWrdDShkK4owiE9pgNlbfsRifHHIlc6PyQcVqs8Y2T9SUQWIO10A/h5Bb5FtMpu17+hWjvNuh82ccElGHM172tGb425+MXWQxnxXm4eFRlRSHHk1FmkxQWp8uIBtJYi7sOTkSTKHbiwFguK4ZKatwMFEJtb5/cz4WkVkLriMdWKkxmU4stMNlRXas35UGefYXJDO1C3QPbbaZSwIA252vqCVHx1e63gSD4thoB7g0p+XMufHRDm7rRUzIXl4IRvMi10SNQwmdjYTmQoF7K+CdeUxEjy2BvHLjRl0++1VocXYIIkholfsubJYvvr4SUgvJpvvHUzTsk+gRb+xk60EE55dLBigHWQX6e2hRpiTVoQ3o+Stkqu7pmyQIFPXhl3XqnxnlXlN6TXVEUBGXpx4Iv2bUV6pEbsP/oA/DKZULJDG0OLH4lbQkaXPIJBugLypDTR3JmvDbo5ehB71AsOsWWlb617WCqXPn7IL8HULlK03+IcsFMx/lOZjHS4xPWaSfOTWs1FIGaJR87wt9UAZjAcrIVQ0ExHeXvjrhzqCTxW0t82wAj2av5VzbDcWBoL5pGSOuARk69GGfEerCduWQdus+TYGlqFdokkzXpoY406RDFUsF5k93faDvsVAba7U/OR72FT4+AFSuYA4r2Y94sBLs8G+Zkpd8JsbNRSk=
  app: flasktaskr-emily
  on:  xirain/flasktaskr

